
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Oct 21 00:40:04 CST 2013
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int id = 14;
  public static final int coma = 10;
  public static final int cc = 7;
  public static final int dec = 11;
  public static final int ca = 6;
  public static final int num = 13;
  public static final int EOF = 0;
  public static final int entero = 12;
  public static final int error = 1;
  public static final int pc = 5;
  public static final int por = 3;
  public static final int pa = 4;
  public static final int mas = 2;
  public static final int pts = 9;
  public static final int igual = 8;
}

